package com.jacob.fruitoftek.safecrop.sustain.fiis;

import android.content.Intent;
import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.os.Bundle;
import android.util.Log;
import android.widget.ImageView;
import android.widget.TextView;

import androidx.activity.EdgeToEdge;
import androidx.appcompat.app.ActionBar;
import androidx.appcompat.app.AppCompatActivity;
import androidx.core.content.ContextCompat;
import androidx.core.graphics.Insets;
import androidx.core.view.ViewCompat;
import androidx.core.view.WindowCompat;
import androidx.core.view.WindowInsetsCompat;

import com.blogspot.atifsoftwares.circularimageview.CircularImageView;
import com.jacob.fruitoftek.safecrop.R;
import com.squareup.picasso.Picasso;

import java.io.File;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Locale;

public class RecordDetailActivityFIIS extends AppCompatActivity {

    private CircularImageView profileIv;
    private TextView firstNameTv, otherNamesTv, iisq1Tv, iisq2Tv, iisq3Tv, iisq4Tv, iisq5Tv, iisq6Tv, iisq7Tv, iisq8Tv, iisq9Tv, iisq10Tv, iisq11Tv, iisq12Tv, iisq13Tv, iisq14Tv, iisq15Tv, iisq16Tv, iisq17Tv, iisq18Tv, iisq19Tv, iisq20Tv, iisq21Tv, iisq22Tv, iisq23Tv, iisq24Tv, iisq25Tv, iisq26Tv, iisq27Tv, iisq28Tv, iisq29Tv, iisq30Tv, iisq31Tv, iisq32Tv, iisq33Tv, iisq34Tv, iisq35Tv, iisq36Tv, iisq37Tv, iisq38Tv, iisq39Tv, iisq40Tv, iisq41Tv, iisq42Tv, iisq43Tv, iisq44Tv, iisq45Tv, iisq46Tv, iisq47Tv, iisq48Tv, iisq49Tv, iisq50Tv, iisq51Tv, iisq52Tv, iisq53Tv, iisq54Tv, iisq55Tv, iisq56Tv, iisq57Tv, iisq58Tv, iisq59Tv, iisq60Tv, iisq61Tv, iisq62Tv, iisq63Tv, iisq64Tv, iisq65Tv, iisq66Tv, iisq67Tv, iisq68Tv, iisq69Tv, iisq70Tv, iisq71Tv, iisq72Tv, iisq73Tv, iisq74Tv, iisq75Tv, iisq76Tv, iisq77Tv, iisq78Tv, iisq79Tv, iisq80Tv, iisq81Tv, iisq82Tv, iisq83Tv, iisq84Tv, iisq85Tv, iisq86Tv, iisq87Tv, iisq88Tv, iisq89Tv, iisq90Tv, iisq91Tv, iisq92Tv, iisq93Tv, iisq94Tv, iisq95Tv, iisq96Tv, iisq97Tv, iisq98Tv, iisq99Tv, iisq100Tv, iisq101Tv, iisq102Tv, iisq103Tv, iisq104Tv, iisq105Tv, iisq106Tv, iisq107Tv, iisq108Tv, iisq109Tv, iisq110Tv, iisq111Tv, iisq112Tv, iisq113Tv, iisq114Tv, iisq115Tv, iisq116Tv, iisq117Tv, iisq118Tv, iisq119Tv, iisq120Tv, iisq121Tv, iisq122Tv, iisq123Tv, iisq124Tv, iisq125Tv, iisq126Tv, iisq127Tv, iisq128Tv, iisq129Tv, iisq130Tv, iisq131Tv, iisq132Tv, iisq133Tv, iisq134Tv, iisq135Tv, iisq136Tv, iisq137Tv, iisq138Tv, iisq139Tv, iisq140Tv, iisq141Tv, iisq142Tv, iisq143Tv, iisq144Tv, iisq145Tv, iisq146Tv, iisq147Tv, iisq148Tv, iisq149Tv, iisq150Tv, iisq151Tv, iisq152Tv, iisq153Tv, iisq154Tv, iisq155Tv, iisq156Tv, iisq157Tv, iisq158Tv, iisq159Tv, iisq160Tv, iisq161Tv, iisq162Tv, iisq163Tv, iisq164Tv, iisq165Tv, iisq166Tv, iisq167Tv, iisq168Tv, iisq169Tv, iisq170Tv, iisq171Tv, iisq172Tv, iisq173Tv, iisq174Tv, iisq175Tv, iisq176Tv, iisq177Tv, iisq178Tv, iisq179Tv, iisq180Tv, iisq181Tv, iisq182Tv, iisq183Tv, iisq184Tv, iisq185Tv, iisq186Tv, iisq187Tv, iisq188Tv, iisq189Tv, iisq190Tv, iisq191Tv, iisq192Tv, iisq193Tv, iisq194Tv, iisq195Tv, iisq196Tv, addedTimeTv, updateTimeTv;
    private MyFIISDbHelper dbHelper;
    private String recordID;

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        EdgeToEdge.enable(this);
        setContentView(R.layout.activity_record_detail_fiis);

        // Set the status bar appearance
        WindowCompat.setDecorFitsSystemWindows(getWindow(), false);
        getWindow().setStatusBarColor(ContextCompat.getColor(this, R.color.status_bar_brown));

        ViewCompat.setOnApplyWindowInsetsListener(findViewById(R.id.main), (v, insets) -> {
            Insets systemBars = insets.getInsets(WindowInsetsCompat.Type.systemBars());
            v.setPadding(systemBars.left, systemBars.top, systemBars.right, systemBars.bottom);
            return insets;
        });

        ActionBar actionBar = getSupportActionBar();
        if (actionBar != null) {
            actionBar.setTitle("Farmer Details");
            actionBar.setDisplayHomeAsUpEnabled(true);
        }

        Intent intent = getIntent();
        recordID = intent.getStringExtra("ID");

        dbHelper = new MyFIISDbHelper(this);

        firstNameTv = findViewById(R.id.iisfirst_nameTv);
        otherNamesTv = findViewById(R.id.iisother_namesTv);
        iisq1Tv = findViewById(R.id.qiis1Tv);
        iisq2Tv = findViewById(R.id.qiis2Tv);
        iisq3Tv = findViewById(R.id.qiis3Tv);
        iisq4Tv = findViewById(R.id.qiis4Tv);
        iisq5Tv = findViewById(R.id.qiis5Tv);
        iisq6Tv = findViewById(R.id.qiis6Tv);
        iisq7Tv = findViewById(R.id.qiis7Tv);
        iisq8Tv = findViewById(R.id.qiis8Tv);
        iisq9Tv = findViewById(R.id.qiis9Tv);
        iisq10Tv = findViewById(R.id.qiis10Tv);
        iisq11Tv = findViewById(R.id.qiis11Tv);
        iisq12Tv = findViewById(R.id.qiis12Tv);
        iisq13Tv = findViewById(R.id.qiis13Tv);
        iisq14Tv = findViewById(R.id.qiis14Tv);
        iisq15Tv = findViewById(R.id.qiis15Tv);
        iisq16Tv = findViewById(R.id.qiis16Tv);
        iisq17Tv = findViewById(R.id.qiis17Tv);
        iisq18Tv = findViewById(R.id.qiis18Tv);
        iisq19Tv = findViewById(R.id.qiis19Tv);
        iisq20Tv = findViewById(R.id.qiis20Tv);
        iisq21Tv = findViewById(R.id.qiis21Tv);
        iisq22Tv = findViewById(R.id.qiis22Tv);
        iisq23Tv = findViewById(R.id.qiis23Tv);
        iisq24Tv = findViewById(R.id.qiis24Tv);
        iisq25Tv = findViewById(R.id.qiis25Tv);
        iisq26Tv = findViewById(R.id.qiis26Tv);
        iisq27Tv = findViewById(R.id.qiis27Tv);
        iisq28Tv = findViewById(R.id.qiis28Tv);
        iisq29Tv = findViewById(R.id.qiis29Tv);
        iisq30Tv = findViewById(R.id.qiis30Tv);
        iisq31Tv = findViewById(R.id.qiis31Tv);
        iisq32Tv = findViewById(R.id.qiis32Tv);
        iisq33Tv = findViewById(R.id.qiis33Tv);
        iisq34Tv = findViewById(R.id.qiis34Tv);
        iisq35Tv = findViewById(R.id.qiis35Tv);
        iisq36Tv = findViewById(R.id.qiis36Tv);
        iisq37Tv = findViewById(R.id.qiis37Tv);
        iisq38Tv = findViewById(R.id.qiis38Tv);
        iisq39Tv = findViewById(R.id.qiis39Tv);
        iisq40Tv = findViewById(R.id.qiis40Tv);
        iisq41Tv = findViewById(R.id.qiis41Tv);
        iisq42Tv = findViewById(R.id.qiis42Tv);
        iisq43Tv = findViewById(R.id.qiis43Tv);
        iisq44Tv = findViewById(R.id.qiis44Tv);
        iisq45Tv = findViewById(R.id.qiis45Tv);
        iisq46Tv = findViewById(R.id.qiis46Tv);
        iisq47Tv = findViewById(R.id.qiis47Tv);
        iisq48Tv = findViewById(R.id.qiis48Tv);
        iisq49Tv = findViewById(R.id.qiis49Tv);
        iisq50Tv = findViewById(R.id.qiis50Tv);
        iisq51Tv = findViewById(R.id.qiis51Tv);
        iisq52Tv = findViewById(R.id.qiis52Tv);
        iisq53Tv = findViewById(R.id.qiis53Tv);
        iisq54Tv = findViewById(R.id.qiis54Tv);
        iisq55Tv = findViewById(R.id.qiis55Tv);
        iisq56Tv = findViewById(R.id.qiis56Tv);
        iisq57Tv = findViewById(R.id.qiis57Tv);
        iisq58Tv = findViewById(R.id.qiis58Tv);
        iisq59Tv = findViewById(R.id.qiis59Tv);
        iisq60Tv = findViewById(R.id.qiis60Tv);
        iisq61Tv = findViewById(R.id.qiis61Tv);
        iisq62Tv = findViewById(R.id.qiis62Tv);
        iisq63Tv = findViewById(R.id.qiis63Tv);
        iisq64Tv = findViewById(R.id.qiis64Tv);
        iisq65Tv = findViewById(R.id.qiis65Tv);
        iisq66Tv = findViewById(R.id.qiis66Tv);
        iisq67Tv = findViewById(R.id.qiis67Tv);
        iisq68Tv = findViewById(R.id.qiis68Tv);
        iisq69Tv = findViewById(R.id.qiis69Tv);
        iisq70Tv = findViewById(R.id.qiis70Tv);
        iisq71Tv = findViewById(R.id.qiis71Tv);
        iisq72Tv = findViewById(R.id.qiis72Tv);
        iisq73Tv = findViewById(R.id.qiis73Tv);
        iisq74Tv = findViewById(R.id.qiis74Tv);
        iisq75Tv = findViewById(R.id.qiis75Tv);
        iisq76Tv = findViewById(R.id.qiis76Tv);
        iisq77Tv = findViewById(R.id.qiis77Tv);
        iisq78Tv = findViewById(R.id.qiis78Tv);
        iisq79Tv = findViewById(R.id.qiis79Tv);
        iisq80Tv = findViewById(R.id.qiis80Tv);
        iisq81Tv = findViewById(R.id.qiis81Tv);
        iisq82Tv = findViewById(R.id.qiis82Tv);
        iisq83Tv = findViewById(R.id.qiis83Tv);
        iisq84Tv = findViewById(R.id.qiis84Tv);
        iisq85Tv = findViewById(R.id.qiis85Tv);
        iisq86Tv = findViewById(R.id.qiis86Tv);
        iisq87Tv = findViewById(R.id.qiis87Tv);
        iisq88Tv = findViewById(R.id.qiis88Tv);
        iisq89Tv = findViewById(R.id.qiis89Tv);
        iisq90Tv = findViewById(R.id.qiis90Tv);
        iisq91Tv = findViewById(R.id.qiis91Tv);
        iisq92Tv = findViewById(R.id.qiis92Tv);
        iisq93Tv = findViewById(R.id.qiis93Tv);
        iisq94Tv = findViewById(R.id.qiis94Tv);
        iisq95Tv = findViewById(R.id.qiis95Tv);
        iisq96Tv = findViewById(R.id.qiis96Tv);
        iisq97Tv = findViewById(R.id.qiis97Tv);
        iisq98Tv = findViewById(R.id.qiis98Tv);
        iisq99Tv = findViewById(R.id.qiis99Tv);
        iisq100Tv = findViewById(R.id.qiis100Tv);
        iisq101Tv = findViewById(R.id.qiis101Tv);
        iisq102Tv = findViewById(R.id.qiis102Tv);
        iisq103Tv = findViewById(R.id.qiis103Tv);
        iisq104Tv = findViewById(R.id.qiis104Tv);
        iisq105Tv = findViewById(R.id.qiis105Tv);
        iisq106Tv = findViewById(R.id.qiis106Tv);
        iisq107Tv = findViewById(R.id.qiis107Tv);
        iisq108Tv = findViewById(R.id.qiis108Tv);
        iisq109Tv = findViewById(R.id.qiis109Tv);
        iisq110Tv = findViewById(R.id.qiis110Tv);
        iisq111Tv = findViewById(R.id.qiis111Tv);
        iisq112Tv = findViewById(R.id.qiis112Tv);
        iisq113Tv = findViewById(R.id.qiis113Tv);
        iisq114Tv = findViewById(R.id.qiis114Tv);
        iisq115Tv = findViewById(R.id.qiis115Tv);
        iisq116Tv = findViewById(R.id.qiis116Tv);
        iisq117Tv = findViewById(R.id.qiis117Tv);
        iisq118Tv = findViewById(R.id.qiis118Tv);
        iisq119Tv = findViewById(R.id.qiis119Tv);
        iisq120Tv = findViewById(R.id.qiis120Tv);
        iisq121Tv = findViewById(R.id.qiis121Tv);
        iisq122Tv = findViewById(R.id.qiis122Tv);
        iisq123Tv = findViewById(R.id.qiis123Tv);
        iisq124Tv = findViewById(R.id.qiis124Tv);
        iisq125Tv = findViewById(R.id.qiis125Tv);
        iisq126Tv = findViewById(R.id.qiis126Tv);
        iisq127Tv = findViewById(R.id.qiis127Tv);
        iisq128Tv = findViewById(R.id.qiis128Tv);
        iisq129Tv = findViewById(R.id.qiis129Tv);
        iisq130Tv = findViewById(R.id.qiis130Tv);
        iisq131Tv = findViewById(R.id.qiis131Tv);
        iisq132Tv = findViewById(R.id.qiis132Tv);
        iisq133Tv = findViewById(R.id.qiis133Tv);
        iisq134Tv = findViewById(R.id.qiis134Tv);
        iisq135Tv = findViewById(R.id.qiis135Tv);
        iisq136Tv = findViewById(R.id.qiis136Tv);
        iisq137Tv = findViewById(R.id.qiis137Tv);
        iisq138Tv = findViewById(R.id.qiis138Tv);
        iisq139Tv = findViewById(R.id.qiis139Tv);
        iisq140Tv = findViewById(R.id.qiis140Tv);
        iisq141Tv = findViewById(R.id.qiis141Tv);
        iisq142Tv = findViewById(R.id.qiis142Tv);
        iisq143Tv = findViewById(R.id.qiis143Tv);
        iisq144Tv = findViewById(R.id.qiis144Tv);
        iisq145Tv = findViewById(R.id.qiis145Tv);
        iisq146Tv = findViewById(R.id.qiis146Tv);
        iisq147Tv = findViewById(R.id.qiis147Tv);
        iisq148Tv = findViewById(R.id.qiis148Tv);
        iisq149Tv = findViewById(R.id.qiis149Tv);
        iisq150Tv = findViewById(R.id.qiis150Tv);
        iisq151Tv = findViewById(R.id.qiis151Tv);
        iisq152Tv = findViewById(R.id.qiis152Tv);
        iisq153Tv = findViewById(R.id.qiis153Tv);
        iisq154Tv = findViewById(R.id.qiis154Tv);
        iisq155Tv = findViewById(R.id.qiis155Tv);
        iisq156Tv = findViewById(R.id.qiis156Tv);
        iisq157Tv = findViewById(R.id.qiis157Tv);
        iisq158Tv = findViewById(R.id.qiis158Tv);
        iisq159Tv = findViewById(R.id.qiis159Tv);
        iisq160Tv = findViewById(R.id.qiis160Tv);
        iisq161Tv = findViewById(R.id.qiis161Tv);
        iisq162Tv = findViewById(R.id.qiis162Tv);
        iisq163Tv = findViewById(R.id.qiis163Tv);
        iisq164Tv = findViewById(R.id.qiis164Tv);
        iisq165Tv = findViewById(R.id.qiis165Tv);
        iisq166Tv = findViewById(R.id.qiis166Tv);
        iisq167Tv = findViewById(R.id.qiis167Tv);
        iisq168Tv = findViewById(R.id.qiis168Tv);
        iisq169Tv = findViewById(R.id.qiis169Tv);
        iisq170Tv = findViewById(R.id.qiis170Tv);
        iisq171Tv = findViewById(R.id.qiis171Tv);
        iisq172Tv = findViewById(R.id.qiis172Tv);
        iisq173Tv = findViewById(R.id.qiis173Tv);
        iisq174Tv = findViewById(R.id.qiis174Tv);
        iisq175Tv = findViewById(R.id.qiis175Tv);
        iisq176Tv = findViewById(R.id.qiis176Tv);
        iisq177Tv = findViewById(R.id.qiis177Tv);
        iisq178Tv = findViewById(R.id.qiis178Tv);
        iisq179Tv = findViewById(R.id.qiis179Tv);
        iisq180Tv = findViewById(R.id.qiis180Tv);
        iisq181Tv = findViewById(R.id.qiis181Tv);
        iisq182Tv = findViewById(R.id.qiis182Tv);
        iisq183Tv = findViewById(R.id.qiis183Tv);
        iisq184Tv = findViewById(R.id.qiis184Tv);
        iisq185Tv = findViewById(R.id.qiis185Tv);
        iisq186Tv = findViewById(R.id.qiis186Tv);
        iisq187Tv = findViewById(R.id.qiis187Tv);
        iisq188Tv = findViewById(R.id.qiis188Tv);
        iisq189Tv = findViewById(R.id.qiis189Tv);
        iisq190Tv = findViewById(R.id.qiis190Tv);
        iisq191Tv = findViewById(R.id.qiis191Tv);
        iisq192Tv = findViewById(R.id.qiis192Tv);
        iisq193Tv = findViewById(R.id.qiis193Tv);
        iisq194Tv = findViewById(R.id.qiis194Tv);
        iisq195Tv = findViewById(R.id.qiis195Tv);
        iisq196Tv = findViewById(R.id.qiis196Tv);
        profileIv = findViewById(R.id.profileIV);
        addedTimeTv = findViewById(R.id.addedTimeTv);
        updateTimeTv = findViewById(R.id.updateTimeTv);

        if (recordID != null) {
            showRecordDetails();
        } else {
            throw new IllegalArgumentException("Record ID is null");
        }
    }

    private void showRecordDetails() {
        String selectQuery = "SELECT * FROM " + ConstansFIIS.TABLE_NAME + " WHERE " + ConstansFIIS.COLUMN_ID + " = ?";
        SQLiteDatabase db = dbHelper.getReadableDatabase();
        try (Cursor cursor = db.rawQuery(selectQuery, new String[]{recordID})) {
            if (cursor.moveToFirst()) {
                String firstName = cursor.getString(cursor.getColumnIndexOrThrow(ConstansFIIS.COLUMN_FIRST_NAME));
                String otherNames = cursor.getString(cursor.getColumnIndexOrThrow(ConstansFIIS.COLUMN_OTHER_NAMES));
                String questionfiis1 = cursor.getString(cursor.getColumnIndexOrThrow(ConstansFIIS.COLUMN_QUESTIONFIIS1));
                String questionfiis2 = cursor.getString(cursor.getColumnIndexOrThrow(ConstansFIIS.COLUMN_QUESTIONFIIS2));
                String questionfiis3 = cursor.getString(cursor.getColumnIndexOrThrow(ConstansFIIS.COLUMN_QUESTIONFIIS3));
                String questionfiis4 = cursor.getString(cursor.getColumnIndexOrThrow(ConstansFIIS.COLUMN_QUESTIONFIIS4));
                String questionfiis5 = cursor.getString(cursor.getColumnIndexOrThrow(ConstansFIIS.COLUMN_QUESTIONFIIS5));
                String questionfiis6 = cursor.getString(cursor.getColumnIndexOrThrow(ConstansFIIS.COLUMN_QUESTIONFIIS6));
                String questionfiis7 = cursor.getString(cursor.getColumnIndexOrThrow(ConstansFIIS.COLUMN_QUESTIONFIIS7));
                String questionfiis8 = cursor.getString(cursor.getColumnIndexOrThrow(ConstansFIIS.COLUMN_QUESTIONFIIS8));
                String questionfiis9 = cursor.getString(cursor.getColumnIndexOrThrow(ConstansFIIS.COLUMN_QUESTIONFIIS9));
                String questionfiis10 = cursor.getString(cursor.getColumnIndexOrThrow(ConstansFIIS.COLUMN_QUESTIONFIIS10));
                String questionfiis11 = cursor.getString(cursor.getColumnIndexOrThrow(ConstansFIIS.COLUMN_QUESTIONFIIS11));
                String questionfiis12 = cursor.getString(cursor.getColumnIndexOrThrow(ConstansFIIS.COLUMN_QUESTIONFIIS12));
                String questionfiis13 = cursor.getString(cursor.getColumnIndexOrThrow(ConstansFIIS.COLUMN_QUESTIONFIIS13));
                String questionfiis14 = cursor.getString(cursor.getColumnIndexOrThrow(ConstansFIIS.COLUMN_QUESTIONFIIS14));
                String questionfiis15 = cursor.getString(cursor.getColumnIndexOrThrow(ConstansFIIS.COLUMN_QUESTIONFIIS15));
                String questionfiis16 = cursor.getString(cursor.getColumnIndexOrThrow(ConstansFIIS.COLUMN_QUESTIONFIIS16));
                String questionfiis17 = cursor.getString(cursor.getColumnIndexOrThrow(ConstansFIIS.COLUMN_QUESTIONFIIS17));
                String questionfiis18 = cursor.getString(cursor.getColumnIndexOrThrow(ConstansFIIS.COLUMN_QUESTIONFIIS18));
                String questionfiis19 = cursor.getString(cursor.getColumnIndexOrThrow(ConstansFIIS.COLUMN_QUESTIONFIIS19));
                String questionfiis20 = cursor.getString(cursor.getColumnIndexOrThrow(ConstansFIIS.COLUMN_QUESTIONFIIS20));
                String questionfiis21 = cursor.getString(cursor.getColumnIndexOrThrow(ConstansFIIS.COLUMN_QUESTIONFIIS21));
                String questionfiis22 = cursor.getString(cursor.getColumnIndexOrThrow(ConstansFIIS.COLUMN_QUESTIONFIIS22));
                String questionfiis23 = cursor.getString(cursor.getColumnIndexOrThrow(ConstansFIIS.COLUMN_QUESTIONFIIS23));
                String questionfiis24 = cursor.getString(cursor.getColumnIndexOrThrow(ConstansFIIS.COLUMN_QUESTIONFIIS24));
                String questionfiis25 = cursor.getString(cursor.getColumnIndexOrThrow(ConstansFIIS.COLUMN_QUESTIONFIIS25));
                String questionfiis26 = cursor.getString(cursor.getColumnIndexOrThrow(ConstansFIIS.COLUMN_QUESTIONFIIS26));
                String questionfiis27 = cursor.getString(cursor.getColumnIndexOrThrow(ConstansFIIS.COLUMN_QUESTIONFIIS27));
                String questionfiis28 = cursor.getString(cursor.getColumnIndexOrThrow(ConstansFIIS.COLUMN_QUESTIONFIIS28));
                String questionfiis29 = cursor.getString(cursor.getColumnIndexOrThrow(ConstansFIIS.COLUMN_QUESTIONFIIS29));
                String questionfiis30 = cursor.getString(cursor.getColumnIndexOrThrow(ConstansFIIS.COLUMN_QUESTIONFIIS30));
                String questionfiis31 = cursor.getString(cursor.getColumnIndexOrThrow(ConstansFIIS.COLUMN_QUESTIONFIIS31));
                String questionfiis32 = cursor.getString(cursor.getColumnIndexOrThrow(ConstansFIIS.COLUMN_QUESTIONFIIS32));
                String questionfiis33 = cursor.getString(cursor.getColumnIndexOrThrow(ConstansFIIS.COLUMN_QUESTIONFIIS33));
                String questionfiis34 = cursor.getString(cursor.getColumnIndexOrThrow(ConstansFIIS.COLUMN_QUESTIONFIIS34));
                String questionfiis35 = cursor.getString(cursor.getColumnIndexOrThrow(ConstansFIIS.COLUMN_QUESTIONFIIS35));
                String questionfiis36 = cursor.getString(cursor.getColumnIndexOrThrow(ConstansFIIS.COLUMN_QUESTIONFIIS36));
                String questionfiis37 = cursor.getString(cursor.getColumnIndexOrThrow(ConstansFIIS.COLUMN_QUESTIONFIIS37));
                String questionfiis38 = cursor.getString(cursor.getColumnIndexOrThrow(ConstansFIIS.COLUMN_QUESTIONFIIS38));
                String questionfiis39 = cursor.getString(cursor.getColumnIndexOrThrow(ConstansFIIS.COLUMN_QUESTIONFIIS39));
                String questionfiis40 = cursor.getString(cursor.getColumnIndexOrThrow(ConstansFIIS.COLUMN_QUESTIONFIIS40));
                String questionfiis41 = cursor.getString(cursor.getColumnIndexOrThrow(ConstansFIIS.COLUMN_QUESTIONFIIS41));
                String questionfiis42 = cursor.getString(cursor.getColumnIndexOrThrow(ConstansFIIS.COLUMN_QUESTIONFIIS42));
                String questionfiis43 = cursor.getString(cursor.getColumnIndexOrThrow(ConstansFIIS.COLUMN_QUESTIONFIIS43));
                String questionfiis44 = cursor.getString(cursor.getColumnIndexOrThrow(ConstansFIIS.COLUMN_QUESTIONFIIS44));
                String questionfiis45 = cursor.getString(cursor.getColumnIndexOrThrow(ConstansFIIS.COLUMN_QUESTIONFIIS45));
                String questionfiis46 = cursor.getString(cursor.getColumnIndexOrThrow(ConstansFIIS.COLUMN_QUESTIONFIIS46));
                String questionfiis47 = cursor.getString(cursor.getColumnIndexOrThrow(ConstansFIIS.COLUMN_QUESTIONFIIS47));
                String questionfiis48 = cursor.getString(cursor.getColumnIndexOrThrow(ConstansFIIS.COLUMN_QUESTIONFIIS48));
                String questionfiis49 = cursor.getString(cursor.getColumnIndexOrThrow(ConstansFIIS.COLUMN_QUESTIONFIIS49));
                String questionfiis50 = cursor.getString(cursor.getColumnIndexOrThrow(ConstansFIIS.COLUMN_QUESTIONFIIS50));
                String questionfiis51 = cursor.getString(cursor.getColumnIndexOrThrow(ConstansFIIS.COLUMN_QUESTIONFIIS51));
                String questionfiis52 = cursor.getString(cursor.getColumnIndexOrThrow(ConstansFIIS.COLUMN_QUESTIONFIIS52));
                String questionfiis53 = cursor.getString(cursor.getColumnIndexOrThrow(ConstansFIIS.COLUMN_QUESTIONFIIS53));
                String questionfiis54 = cursor.getString(cursor.getColumnIndexOrThrow(ConstansFIIS.COLUMN_QUESTIONFIIS54));
                String questionfiis55 = cursor.getString(cursor.getColumnIndexOrThrow(ConstansFIIS.COLUMN_QUESTIONFIIS55));
                String questionfiis56 = cursor.getString(cursor.getColumnIndexOrThrow(ConstansFIIS.COLUMN_QUESTIONFIIS56));
                String questionfiis57 = cursor.getString(cursor.getColumnIndexOrThrow(ConstansFIIS.COLUMN_QUESTIONFIIS57));
                String questionfiis58 = cursor.getString(cursor.getColumnIndexOrThrow(ConstansFIIS.COLUMN_QUESTIONFIIS58));
                String questionfiis59 = cursor.getString(cursor.getColumnIndexOrThrow(ConstansFIIS.COLUMN_QUESTIONFIIS59));
                String questionfiis60 = cursor.getString(cursor.getColumnIndexOrThrow(ConstansFIIS.COLUMN_QUESTIONFIIS60));
                String questionfiis61 = cursor.getString(cursor.getColumnIndexOrThrow(ConstansFIIS.COLUMN_QUESTIONFIIS61));
                String questionfiis62 = cursor.getString(cursor.getColumnIndexOrThrow(ConstansFIIS.COLUMN_QUESTIONFIIS62));
                String questionfiis63 = cursor.getString(cursor.getColumnIndexOrThrow(ConstansFIIS.COLUMN_QUESTIONFIIS63));
                String questionfiis64 = cursor.getString(cursor.getColumnIndexOrThrow(ConstansFIIS.COLUMN_QUESTIONFIIS64));
                String questionfiis65 = cursor.getString(cursor.getColumnIndexOrThrow(ConstansFIIS.COLUMN_QUESTIONFIIS65));
                String questionfiis66 = cursor.getString(cursor.getColumnIndexOrThrow(ConstansFIIS.COLUMN_QUESTIONFIIS66));
                String questionfiis67 = cursor.getString(cursor.getColumnIndexOrThrow(ConstansFIIS.COLUMN_QUESTIONFIIS67));
                String questionfiis68 = cursor.getString(cursor.getColumnIndexOrThrow(ConstansFIIS.COLUMN_QUESTIONFIIS68));
                String questionfiis69 = cursor.getString(cursor.getColumnIndexOrThrow(ConstansFIIS.COLUMN_QUESTIONFIIS69));
                String questionfiis70 = cursor.getString(cursor.getColumnIndexOrThrow(ConstansFIIS.COLUMN_QUESTIONFIIS70));
                String questionfiis71 = cursor.getString(cursor.getColumnIndexOrThrow(ConstansFIIS.COLUMN_QUESTIONFIIS71));
                String questionfiis72 = cursor.getString(cursor.getColumnIndexOrThrow(ConstansFIIS.COLUMN_QUESTIONFIIS72));
                String questionfiis73 = cursor.getString(cursor.getColumnIndexOrThrow(ConstansFIIS.COLUMN_QUESTIONFIIS73));
                String questionfiis74 = cursor.getString(cursor.getColumnIndexOrThrow(ConstansFIIS.COLUMN_QUESTIONFIIS74));
                String questionfiis75 = cursor.getString(cursor.getColumnIndexOrThrow(ConstansFIIS.COLUMN_QUESTIONFIIS75));
                String questionfiis76 = cursor.getString(cursor.getColumnIndexOrThrow(ConstansFIIS.COLUMN_QUESTIONFIIS76));
                String questionfiis77 = cursor.getString(cursor.getColumnIndexOrThrow(ConstansFIIS.COLUMN_QUESTIONFIIS77));
                String questionfiis78 = cursor.getString(cursor.getColumnIndexOrThrow(ConstansFIIS.COLUMN_QUESTIONFIIS78));
                String questionfiis79 = cursor.getString(cursor.getColumnIndexOrThrow(ConstansFIIS.COLUMN_QUESTIONFIIS79));
                String questionfiis80 = cursor.getString(cursor.getColumnIndexOrThrow(ConstansFIIS.COLUMN_QUESTIONFIIS80));
                String questionfiis81 = cursor.getString(cursor.getColumnIndexOrThrow(ConstansFIIS.COLUMN_QUESTIONFIIS81));
                String questionfiis82 = cursor.getString(cursor.getColumnIndexOrThrow(ConstansFIIS.COLUMN_QUESTIONFIIS82));
                String questionfiis83 = cursor.getString(cursor.getColumnIndexOrThrow(ConstansFIIS.COLUMN_QUESTIONFIIS83));
                String questionfiis84 = cursor.getString(cursor.getColumnIndexOrThrow(ConstansFIIS.COLUMN_QUESTIONFIIS84));
                String questionfiis85 = cursor.getString(cursor.getColumnIndexOrThrow(ConstansFIIS.COLUMN_QUESTIONFIIS85));
                String questionfiis86 = cursor.getString(cursor.getColumnIndexOrThrow(ConstansFIIS.COLUMN_QUESTIONFIIS86));
                String questionfiis87 = cursor.getString(cursor.getColumnIndexOrThrow(ConstansFIIS.COLUMN_QUESTIONFIIS87));
                String questionfiis88 = cursor.getString(cursor.getColumnIndexOrThrow(ConstansFIIS.COLUMN_QUESTIONFIIS88));
                String questionfiis89 = cursor.getString(cursor.getColumnIndexOrThrow(ConstansFIIS.COLUMN_QUESTIONFIIS89));
                String questionfiis90 = cursor.getString(cursor.getColumnIndexOrThrow(ConstansFIIS.COLUMN_QUESTIONFIIS90));
                String questionfiis91 = cursor.getString(cursor.getColumnIndexOrThrow(ConstansFIIS.COLUMN_QUESTIONFIIS91));
                String questionfiis92 = cursor.getString(cursor.getColumnIndexOrThrow(ConstansFIIS.COLUMN_QUESTIONFIIS92));
                String questionfiis93 = cursor.getString(cursor.getColumnIndexOrThrow(ConstansFIIS.COLUMN_QUESTIONFIIS93));
                String questionfiis94 = cursor.getString(cursor.getColumnIndexOrThrow(ConstansFIIS.COLUMN_QUESTIONFIIS94));
                String questionfiis95 = cursor.getString(cursor.getColumnIndexOrThrow(ConstansFIIS.COLUMN_QUESTIONFIIS95));
                String questionfiis96 = cursor.getString(cursor.getColumnIndexOrThrow(ConstansFIIS.COLUMN_QUESTIONFIIS96));
                String questionfiis97 = cursor.getString(cursor.getColumnIndexOrThrow(ConstansFIIS.COLUMN_QUESTIONFIIS97));
                String questionfiis98 = cursor.getString(cursor.getColumnIndexOrThrow(ConstansFIIS.COLUMN_QUESTIONFIIS98));
                String questionfiis99 = cursor.getString(cursor.getColumnIndexOrThrow(ConstansFIIS.COLUMN_QUESTIONFIIS99));
                String questionfiis100 = cursor.getString(cursor.getColumnIndexOrThrow(ConstansFIIS.COLUMN_QUESTIONFIIS100));
                String questionfiis101 = cursor.getString(cursor.getColumnIndexOrThrow(ConstansFIIS.COLUMN_QUESTIONFIIS101));
                String questionfiis102 = cursor.getString(cursor.getColumnIndexOrThrow(ConstansFIIS.COLUMN_QUESTIONFIIS102));
                String questionfiis103 = cursor.getString(cursor.getColumnIndexOrThrow(ConstansFIIS.COLUMN_QUESTIONFIIS103));
                String questionfiis104 = cursor.getString(cursor.getColumnIndexOrThrow(ConstansFIIS.COLUMN_QUESTIONFIIS104));
                String questionfiis105 = cursor.getString(cursor.getColumnIndexOrThrow(ConstansFIIS.COLUMN_QUESTIONFIIS105));
                String questionfiis106 = cursor.getString(cursor.getColumnIndexOrThrow(ConstansFIIS.COLUMN_QUESTIONFIIS106));
                String questionfiis107 = cursor.getString(cursor.getColumnIndexOrThrow(ConstansFIIS.COLUMN_QUESTIONFIIS107));
                String questionfiis108 = cursor.getString(cursor.getColumnIndexOrThrow(ConstansFIIS.COLUMN_QUESTIONFIIS108));
                String questionfiis109 = cursor.getString(cursor.getColumnIndexOrThrow(ConstansFIIS.COLUMN_QUESTIONFIIS109));
                String questionfiis110 = cursor.getString(cursor.getColumnIndexOrThrow(ConstansFIIS.COLUMN_QUESTIONFIIS110));
                String questionfiis111 = cursor.getString(cursor.getColumnIndexOrThrow(ConstansFIIS.COLUMN_QUESTIONFIIS111));
                String questionfiis112 = cursor.getString(cursor.getColumnIndexOrThrow(ConstansFIIS.COLUMN_QUESTIONFIIS112));
                String questionfiis113 = cursor.getString(cursor.getColumnIndexOrThrow(ConstansFIIS.COLUMN_QUESTIONFIIS113));
                String questionfiis114 = cursor.getString(cursor.getColumnIndexOrThrow(ConstansFIIS.COLUMN_QUESTIONFIIS114));
                String questionfiis115 = cursor.getString(cursor.getColumnIndexOrThrow(ConstansFIIS.COLUMN_QUESTIONFIIS115));
                String questionfiis116 = cursor.getString(cursor.getColumnIndexOrThrow(ConstansFIIS.COLUMN_QUESTIONFIIS116));
                String questionfiis117 = cursor.getString(cursor.getColumnIndexOrThrow(ConstansFIIS.COLUMN_QUESTIONFIIS117));
                String questionfiis118 = cursor.getString(cursor.getColumnIndexOrThrow(ConstansFIIS.COLUMN_QUESTIONFIIS118));
                String questionfiis119 = cursor.getString(cursor.getColumnIndexOrThrow(ConstansFIIS.COLUMN_QUESTIONFIIS119));
                String questionfiis120 = cursor.getString(cursor.getColumnIndexOrThrow(ConstansFIIS.COLUMN_QUESTIONFIIS120));
                String questionfiis121 = cursor.getString(cursor.getColumnIndexOrThrow(ConstansFIIS.COLUMN_QUESTIONFIIS121));
                String questionfiis122 = cursor.getString(cursor.getColumnIndexOrThrow(ConstansFIIS.COLUMN_QUESTIONFIIS122));
                String questionfiis123 = cursor.getString(cursor.getColumnIndexOrThrow(ConstansFIIS.COLUMN_QUESTIONFIIS123));
                String questionfiis124 = cursor.getString(cursor.getColumnIndexOrThrow(ConstansFIIS.COLUMN_QUESTIONFIIS124));
                String questionfiis125 = cursor.getString(cursor.getColumnIndexOrThrow(ConstansFIIS.COLUMN_QUESTIONFIIS125));
                String questionfiis126 = cursor.getString(cursor.getColumnIndexOrThrow(ConstansFIIS.COLUMN_QUESTIONFIIS126));
                String questionfiis127 = cursor.getString(cursor.getColumnIndexOrThrow(ConstansFIIS.COLUMN_QUESTIONFIIS127));
                String questionfiis128 = cursor.getString(cursor.getColumnIndexOrThrow(ConstansFIIS.COLUMN_QUESTIONFIIS128));
                String questionfiis129 = cursor.getString(cursor.getColumnIndexOrThrow(ConstansFIIS.COLUMN_QUESTIONFIIS129));
                String questionfiis130 = cursor.getString(cursor.getColumnIndexOrThrow(ConstansFIIS.COLUMN_QUESTIONFIIS130));
                String questionfiis131 = cursor.getString(cursor.getColumnIndexOrThrow(ConstansFIIS.COLUMN_QUESTIONFIIS131));
                String questionfiis132 = cursor.getString(cursor.getColumnIndexOrThrow(ConstansFIIS.COLUMN_QUESTIONFIIS132));
                String questionfiis133 = cursor.getString(cursor.getColumnIndexOrThrow(ConstansFIIS.COLUMN_QUESTIONFIIS133));
                String questionfiis134 = cursor.getString(cursor.getColumnIndexOrThrow(ConstansFIIS.COLUMN_QUESTIONFIIS134));
                String questionfiis135 = cursor.getString(cursor.getColumnIndexOrThrow(ConstansFIIS.COLUMN_QUESTIONFIIS135));
                String questionfiis136 = cursor.getString(cursor.getColumnIndexOrThrow(ConstansFIIS.COLUMN_QUESTIONFIIS136));
                String questionfiis137 = cursor.getString(cursor.getColumnIndexOrThrow(ConstansFIIS.COLUMN_QUESTIONFIIS137));
                String questionfiis138 = cursor.getString(cursor.getColumnIndexOrThrow(ConstansFIIS.COLUMN_QUESTIONFIIS138));
                String questionfiis139 = cursor.getString(cursor.getColumnIndexOrThrow(ConstansFIIS.COLUMN_QUESTIONFIIS139));
                String questionfiis140 = cursor.getString(cursor.getColumnIndexOrThrow(ConstansFIIS.COLUMN_QUESTIONFIIS140));
                String questionfiis141 = cursor.getString(cursor.getColumnIndexOrThrow(ConstansFIIS.COLUMN_QUESTIONFIIS141));
                String questionfiis142 = cursor.getString(cursor.getColumnIndexOrThrow(ConstansFIIS.COLUMN_QUESTIONFIIS142));
                String questionfiis143 = cursor.getString(cursor.getColumnIndexOrThrow(ConstansFIIS.COLUMN_QUESTIONFIIS143));
                String questionfiis144 = cursor.getString(cursor.getColumnIndexOrThrow(ConstansFIIS.COLUMN_QUESTIONFIIS144));
                String questionfiis145 = cursor.getString(cursor.getColumnIndexOrThrow(ConstansFIIS.COLUMN_QUESTIONFIIS145));
                String questionfiis146 = cursor.getString(cursor.getColumnIndexOrThrow(ConstansFIIS.COLUMN_QUESTIONFIIS146));
                String questionfiis147 = cursor.getString(cursor.getColumnIndexOrThrow(ConstansFIIS.COLUMN_QUESTIONFIIS147));
                String questionfiis148 = cursor.getString(cursor.getColumnIndexOrThrow(ConstansFIIS.COLUMN_QUESTIONFIIS148));
                String questionfiis149 = cursor.getString(cursor.getColumnIndexOrThrow(ConstansFIIS.COLUMN_QUESTIONFIIS149));
                String questionfiis150 = cursor.getString(cursor.getColumnIndexOrThrow(ConstansFIIS.COLUMN_QUESTIONFIIS150));
                String questionfiis151 = cursor.getString(cursor.getColumnIndexOrThrow(ConstansFIIS.COLUMN_QUESTIONFIIS151));
                String questionfiis152 = cursor.getString(cursor.getColumnIndexOrThrow(ConstansFIIS.COLUMN_QUESTIONFIIS152));
                String questionfiis153 = cursor.getString(cursor.getColumnIndexOrThrow(ConstansFIIS.COLUMN_QUESTIONFIIS153));
                String questionfiis154 = cursor.getString(cursor.getColumnIndexOrThrow(ConstansFIIS.COLUMN_QUESTIONFIIS154));
                String questionfiis155 = cursor.getString(cursor.getColumnIndexOrThrow(ConstansFIIS.COLUMN_QUESTIONFIIS155));
                String questionfiis156 = cursor.getString(cursor.getColumnIndexOrThrow(ConstansFIIS.COLUMN_QUESTIONFIIS156));
                String questionfiis157 = cursor.getString(cursor.getColumnIndexOrThrow(ConstansFIIS.COLUMN_QUESTIONFIIS157));
                String questionfiis158 = cursor.getString(cursor.getColumnIndexOrThrow(ConstansFIIS.COLUMN_QUESTIONFIIS158));
                String questionfiis159 = cursor.getString(cursor.getColumnIndexOrThrow(ConstansFIIS.COLUMN_QUESTIONFIIS159));
                String questionfiis160 = cursor.getString(cursor.getColumnIndexOrThrow(ConstansFIIS.COLUMN_QUESTIONFIIS160));
                String questionfiis161 = cursor.getString(cursor.getColumnIndexOrThrow(ConstansFIIS.COLUMN_QUESTIONFIIS161));
                String questionfiis162 = cursor.getString(cursor.getColumnIndexOrThrow(ConstansFIIS.COLUMN_QUESTIONFIIS162));
                String questionfiis163 = cursor.getString(cursor.getColumnIndexOrThrow(ConstansFIIS.COLUMN_QUESTIONFIIS163));
                String questionfiis164 = cursor.getString(cursor.getColumnIndexOrThrow(ConstansFIIS.COLUMN_QUESTIONFIIS164));
                String questionfiis165 = cursor.getString(cursor.getColumnIndexOrThrow(ConstansFIIS.COLUMN_QUESTIONFIIS165));
                String questionfiis166 = cursor.getString(cursor.getColumnIndexOrThrow(ConstansFIIS.COLUMN_QUESTIONFIIS166));
                String questionfiis167 = cursor.getString(cursor.getColumnIndexOrThrow(ConstansFIIS.COLUMN_QUESTIONFIIS167));
                String questionfiis168 = cursor.getString(cursor.getColumnIndexOrThrow(ConstansFIIS.COLUMN_QUESTIONFIIS168));
                String questionfiis169 = cursor.getString(cursor.getColumnIndexOrThrow(ConstansFIIS.COLUMN_QUESTIONFIIS169));
                String questionfiis170 = cursor.getString(cursor.getColumnIndexOrThrow(ConstansFIIS.COLUMN_QUESTIONFIIS170));
                String questionfiis171 = cursor.getString(cursor.getColumnIndexOrThrow(ConstansFIIS.COLUMN_QUESTIONFIIS171));
                String questionfiis172 = cursor.getString(cursor.getColumnIndexOrThrow(ConstansFIIS.COLUMN_QUESTIONFIIS172));
                String questionfiis173 = cursor.getString(cursor.getColumnIndexOrThrow(ConstansFIIS.COLUMN_QUESTIONFIIS173));
                String questionfiis174 = cursor.getString(cursor.getColumnIndexOrThrow(ConstansFIIS.COLUMN_QUESTIONFIIS174));
                String questionfiis175 = cursor.getString(cursor.getColumnIndexOrThrow(ConstansFIIS.COLUMN_QUESTIONFIIS175));
                String questionfiis176 = cursor.getString(cursor.getColumnIndexOrThrow(ConstansFIIS.COLUMN_QUESTIONFIIS176));
                String questionfiis177 = cursor.getString(cursor.getColumnIndexOrThrow(ConstansFIIS.COLUMN_QUESTIONFIIS177));
                String questionfiis178 = cursor.getString(cursor.getColumnIndexOrThrow(ConstansFIIS.COLUMN_QUESTIONFIIS178));
                String questionfiis179 = cursor.getString(cursor.getColumnIndexOrThrow(ConstansFIIS.COLUMN_QUESTIONFIIS179));
                String questionfiis180 = cursor.getString(cursor.getColumnIndexOrThrow(ConstansFIIS.COLUMN_QUESTIONFIIS180));
                String questionfiis181 = cursor.getString(cursor.getColumnIndexOrThrow(ConstansFIIS.COLUMN_QUESTIONFIIS181));
                String questionfiis182 = cursor.getString(cursor.getColumnIndexOrThrow(ConstansFIIS.COLUMN_QUESTIONFIIS182));
                String questionfiis183 = cursor.getString(cursor.getColumnIndexOrThrow(ConstansFIIS.COLUMN_QUESTIONFIIS183));
                String questionfiis184 = cursor.getString(cursor.getColumnIndexOrThrow(ConstansFIIS.COLUMN_QUESTIONFIIS184));
                String questionfiis185 = cursor.getString(cursor.getColumnIndexOrThrow(ConstansFIIS.COLUMN_QUESTIONFIIS185));
                String questionfiis186 = cursor.getString(cursor.getColumnIndexOrThrow(ConstansFIIS.COLUMN_QUESTIONFIIS186));
                String questionfiis187 = cursor.getString(cursor.getColumnIndexOrThrow(ConstansFIIS.COLUMN_QUESTIONFIIS187));
                String questionfiis188 = cursor.getString(cursor.getColumnIndexOrThrow(ConstansFIIS.COLUMN_QUESTIONFIIS188));
                String questionfiis189 = cursor.getString(cursor.getColumnIndexOrThrow(ConstansFIIS.COLUMN_QUESTIONFIIS189));
                String questionfiis190 = cursor.getString(cursor.getColumnIndexOrThrow(ConstansFIIS.COLUMN_QUESTIONFIIS190));
                String questionfiis191 = cursor.getString(cursor.getColumnIndexOrThrow(ConstansFIIS.COLUMN_QUESTIONFIIS191));
                String questionfiis192 = cursor.getString(cursor.getColumnIndexOrThrow(ConstansFIIS.COLUMN_QUESTIONFIIS192));
                String questionfiis193 = cursor.getString(cursor.getColumnIndexOrThrow(ConstansFIIS.COLUMN_QUESTIONFIIS193));
                String questionfiis194 = cursor.getString(cursor.getColumnIndexOrThrow(ConstansFIIS.COLUMN_QUESTIONFIIS194));
                String questionfiis195 = cursor.getString(cursor.getColumnIndexOrThrow(ConstansFIIS.COLUMN_QUESTIONFIIS195));
                String questionfiis196 = cursor.getString(cursor.getColumnIndexOrThrow(ConstansFIIS.COLUMN_QUESTIONFIIS196));
                String profileImage = cursor.getString(cursor.getColumnIndexOrThrow(ConstansFIIS.COLUMN_PROFILE_IMAGE));
                String creationDate = cursor.getString(cursor.getColumnIndexOrThrow(ConstansFIIS.COLUMN_CREATION_DATE));
                String updateDate = cursor.getString(cursor.getColumnIndexOrThrow(ConstansFIIS.COLUMN_UPDATE_DATE));

                firstNameTv.setText(firstName);
                otherNamesTv.setText(otherNames);
                iisq1Tv.setText(questionfiis1);
                iisq2Tv.setText(questionfiis2);
                iisq3Tv.setText(questionfiis3);
                iisq4Tv.setText(questionfiis4);
                iisq5Tv.setText(questionfiis5);
                iisq6Tv.setText(questionfiis6);
                iisq7Tv.setText(questionfiis7);
                iisq8Tv.setText(questionfiis8);
                iisq9Tv.setText(questionfiis9);
                iisq10Tv.setText(questionfiis10);
                iisq11Tv.setText(questionfiis11);
                iisq12Tv.setText(questionfiis12);
                iisq13Tv.setText(questionfiis13);
                iisq14Tv.setText(questionfiis14);
                iisq15Tv.setText(questionfiis15);
                iisq16Tv.setText(questionfiis16);
                iisq17Tv.setText(questionfiis17);
                iisq18Tv.setText(questionfiis18);
                iisq19Tv.setText(questionfiis19);
                iisq20Tv.setText(questionfiis20);
                iisq21Tv.setText(questionfiis21);
                iisq22Tv.setText(questionfiis22);
                iisq23Tv.setText(questionfiis23);
                iisq24Tv.setText(questionfiis24);
                iisq25Tv.setText(questionfiis25);
                iisq26Tv.setText(questionfiis26);
                iisq27Tv.setText(questionfiis27);
                iisq28Tv.setText(questionfiis28);
                iisq29Tv.setText(questionfiis29);
                iisq30Tv.setText(questionfiis30);
                iisq31Tv.setText(questionfiis31);
                iisq32Tv.setText(questionfiis32);
                iisq33Tv.setText(questionfiis33);
                iisq34Tv.setText(questionfiis34);
                iisq35Tv.setText(questionfiis35);
                iisq36Tv.setText(questionfiis36);
                iisq37Tv.setText(questionfiis37);
                iisq38Tv.setText(questionfiis38);
                iisq39Tv.setText(questionfiis39);
                iisq40Tv.setText(questionfiis40);
                iisq41Tv.setText(questionfiis41);
                iisq42Tv.setText(questionfiis42);
                iisq43Tv.setText(questionfiis43);
                iisq44Tv.setText(questionfiis44);
                iisq45Tv.setText(questionfiis45);
                iisq46Tv.setText(questionfiis46);
                iisq47Tv.setText(questionfiis47);
                iisq48Tv.setText(questionfiis48);
                iisq49Tv.setText(questionfiis49);
                iisq50Tv.setText(questionfiis50);
                iisq51Tv.setText(questionfiis51);
                iisq52Tv.setText(questionfiis52);
                iisq53Tv.setText(questionfiis53);
                iisq54Tv.setText(questionfiis54);
                iisq55Tv.setText(questionfiis55);
                iisq56Tv.setText(questionfiis56);
                iisq57Tv.setText(questionfiis57);
                iisq58Tv.setText(questionfiis58);
                iisq59Tv.setText(questionfiis59);
                iisq60Tv.setText(questionfiis60);
                iisq61Tv.setText(questionfiis61);
                iisq62Tv.setText(questionfiis62);
                iisq63Tv.setText(questionfiis63);
                iisq64Tv.setText(questionfiis64);
                iisq65Tv.setText(questionfiis65);
                iisq66Tv.setText(questionfiis66);
                iisq67Tv.setText(questionfiis67);
                iisq68Tv.setText(questionfiis68);
                iisq69Tv.setText(questionfiis69);
                iisq70Tv.setText(questionfiis70);
                iisq71Tv.setText(questionfiis71);
                iisq72Tv.setText(questionfiis72);
                iisq73Tv.setText(questionfiis73);
                iisq74Tv.setText(questionfiis74);
                iisq75Tv.setText(questionfiis75);
                iisq76Tv.setText(questionfiis76);
                iisq77Tv.setText(questionfiis77);
                iisq78Tv.setText(questionfiis78);
                iisq79Tv.setText(questionfiis79);
                iisq80Tv.setText(questionfiis80);
                iisq81Tv.setText(questionfiis81);
                iisq82Tv.setText(questionfiis82);
                iisq83Tv.setText(questionfiis83);
                iisq84Tv.setText(questionfiis84);
                iisq85Tv.setText(questionfiis85);
                iisq86Tv.setText(questionfiis86);
                iisq87Tv.setText(questionfiis87);
                iisq88Tv.setText(questionfiis88);
                iisq89Tv.setText(questionfiis89);
                iisq90Tv.setText(questionfiis90);
                iisq91Tv.setText(questionfiis91);
                iisq92Tv.setText(questionfiis92);
                iisq93Tv.setText(questionfiis93);
                iisq94Tv.setText(questionfiis94);
                iisq95Tv.setText(questionfiis95);
                iisq96Tv.setText(questionfiis96);
                iisq97Tv.setText(questionfiis97);
                iisq98Tv.setText(questionfiis98);
                iisq99Tv.setText(questionfiis99);
                iisq100Tv.setText(questionfiis100);
                iisq101Tv.setText(questionfiis101);
                iisq102Tv.setText(questionfiis102);
                iisq103Tv.setText(questionfiis103);
                iisq104Tv.setText(questionfiis104);
                iisq105Tv.setText(questionfiis105);
                iisq106Tv.setText(questionfiis106);
                iisq107Tv.setText(questionfiis107);
                iisq108Tv.setText(questionfiis108);
                iisq109Tv.setText(questionfiis109);
                iisq110Tv.setText(questionfiis110);
                iisq111Tv.setText(questionfiis111);
                iisq112Tv.setText(questionfiis112);
                iisq113Tv.setText(questionfiis113);
                iisq114Tv.setText(questionfiis114);
                iisq115Tv.setText(questionfiis115);
                iisq116Tv.setText(questionfiis116);
                iisq117Tv.setText(questionfiis117);
                iisq118Tv.setText(questionfiis118);
                iisq119Tv.setText(questionfiis119);
                iisq120Tv.setText(questionfiis120);
                iisq121Tv.setText(questionfiis121);
                iisq122Tv.setText(questionfiis122);
                iisq123Tv.setText(questionfiis123);
                iisq124Tv.setText(questionfiis124);
                iisq125Tv.setText(questionfiis125);
                iisq126Tv.setText(questionfiis126);
                iisq127Tv.setText(questionfiis127);
                iisq128Tv.setText(questionfiis128);
                iisq129Tv.setText(questionfiis129);
                iisq130Tv.setText(questionfiis130);
                iisq131Tv.setText(questionfiis131);
                iisq132Tv.setText(questionfiis132);
                iisq133Tv.setText(questionfiis133);
                iisq134Tv.setText(questionfiis134);
                iisq135Tv.setText(questionfiis135);
                iisq136Tv.setText(questionfiis136);
                iisq137Tv.setText(questionfiis137);
                iisq138Tv.setText(questionfiis138);
                iisq139Tv.setText(questionfiis139);
                iisq140Tv.setText(questionfiis140);
                iisq141Tv.setText(questionfiis141);
                iisq142Tv.setText(questionfiis142);
                iisq143Tv.setText(questionfiis143);
                iisq144Tv.setText(questionfiis144);
                iisq145Tv.setText(questionfiis145);
                iisq146Tv.setText(questionfiis146);
                iisq147Tv.setText(questionfiis147);
                iisq148Tv.setText(questionfiis148);
                iisq149Tv.setText(questionfiis149);
                iisq150Tv.setText(questionfiis150);
                iisq151Tv.setText(questionfiis151);
                iisq152Tv.setText(questionfiis152);
                iisq153Tv.setText(questionfiis153);
                iisq154Tv.setText(questionfiis154);
                iisq155Tv.setText(questionfiis155);
                iisq156Tv.setText(questionfiis156);
                iisq157Tv.setText(questionfiis157);
                iisq158Tv.setText(questionfiis158);
                iisq159Tv.setText(questionfiis159);
                iisq160Tv.setText(questionfiis160);
                iisq161Tv.setText(questionfiis161);
                iisq162Tv.setText(questionfiis162);
                iisq163Tv.setText(questionfiis163);
                iisq164Tv.setText(questionfiis164);
                iisq165Tv.setText(questionfiis165);
                iisq166Tv.setText(questionfiis166);
                iisq167Tv.setText(questionfiis167);
                iisq168Tv.setText(questionfiis168);
                iisq169Tv.setText(questionfiis169);
                iisq170Tv.setText(questionfiis170);
                iisq171Tv.setText(questionfiis171);
                iisq172Tv.setText(questionfiis172);
                iisq173Tv.setText(questionfiis173);
                iisq174Tv.setText(questionfiis174);
                iisq175Tv.setText(questionfiis175);
                iisq176Tv.setText(questionfiis176);
                iisq177Tv.setText(questionfiis177);
                iisq178Tv.setText(questionfiis178);
                iisq179Tv.setText(questionfiis179);
                iisq180Tv.setText(questionfiis180);
                iisq181Tv.setText(questionfiis181);
                iisq182Tv.setText(questionfiis182);
                iisq183Tv.setText(questionfiis183);
                iisq184Tv.setText(questionfiis184);
                iisq185Tv.setText(questionfiis185);
                iisq186Tv.setText(questionfiis186);
                iisq187Tv.setText(questionfiis187);
                iisq188Tv.setText(questionfiis188);
                iisq189Tv.setText(questionfiis189);
                iisq190Tv.setText(questionfiis190);
                iisq191Tv.setText(questionfiis191);
                iisq192Tv.setText(questionfiis192);
                iisq193Tv.setText(questionfiis193);
                iisq194Tv.setText(questionfiis194);
                iisq195Tv.setText(questionfiis195);
                iisq196Tv.setText(questionfiis196);
                addedTimeTv.setText(creationDate);
                updateTimeTv.setText(updateDate);

                Log.d("RecordDetailActivity", "Profile Image Path: " + profileImage);

                loadImage(profileImage, profileIv);

                addedTimeTv.setText(formatDate(creationDate));
                updateTimeTv.setText(formatDate(updateDate));
            }
        }
    }

    private void loadImage(String imagePath, ImageView imageView) {
        if (imagePath != null && !imagePath.equals("null")) {
            Picasso.get().load(new File(imagePath)).into(imageView);
        } else {
            imageView.setImageResource(R.drawable.ic_person_black);
        }
    }

    private String formatDate(String dateString) {
        SimpleDateFormat inputFormat = new SimpleDateFormat("yyyy-MM-dd HH:mm:ss", Locale.getDefault());
        SimpleDateFormat outputFormat = new SimpleDateFormat("dd/MM/yyyy hh:mm:aa", Locale.getDefault());
        try {
            return outputFormat.format(inputFormat.parse(dateString));
        } catch (ParseException e) {
            e.printStackTrace();
            return "N/A";
        }
    }
}